### ISSUE TITLE
undefined method `new_resource' for Chef::Resource::LvmLogicalVolume

### ISSUE THREAD

**Issue by gawbul** [chef-cookbooks/lvm#102]
### Cookbook version

2.1.2 (also versions 1.4.1+)
### Chef-client version

12.7.2-1 (also tested with 12.4.1-1 and 12.11.18-1)
### Platform Details

CentOS Linux release 7.2.1511 (Core)
### Scenario:

I've created a wrapper around the lvm resource in my own cookbook to create a volume group, with a single logical volume and mount it at a given mount point. However, I receive the following error:

```
       Recipe: my_cookbook::diskmnt
         * my_cookbook_diskmnt[Setup data disk] action create

           ================================================================================
           Error executing action `create` on resource 'my_cookbook_diskmnt[Setup data disk]'
           ================================================================================

           NoMethodError
           -------------
           No resource or method named `new_resource' for `Chef::Resource::LvmLogicalVolume "lv_data"'

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/my_cookbook/providers/diskmnt.rb:35:in `block (3 levels) in class_from_file'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
           /tmp/kitchen/cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'
           /tmp/kitchen/cookbooks/my_cookbook/providers/diskmnt.rb:34:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
           /tmp/kitchen/cookbooks/my_cookbook/providers/diskmnt.rb:29:in `block in class_from_file'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
```

If I call the same code I use in the provider in the recipe (i.e. without wrapping it in a provider), it works fine? Something to do with nested resources?
### Steps to Reproduce:

Create a resource and provider in a cookbook and call the lvm resource from that, e.g.

**my_cookbook/resources/diskmnt.rb**

```
actions :create
default_action :create

attribute :vol_group,       kind_of: String,  required: true
attribute :phys_vol,        kind_of: String,  required: true
attribute :log_vol,         kind_of: String,  required: true
attribute :vol_size,        kind_of: String,  default: '100%VG'
attribute :fs_type,         kind_of: String,  default: 'ext4'
attribute :mount_point,     kind_of: String,  required: true
```

**my_cookbook/provider/diskmnt.rb**

```
action :create do
  # only run if we're set to
  if node['my_cookbook']['diskmnt'] == true
    # install relevant packages and gems
    include_recipe 'lvm::default'

    vol_group = new_resource.vol_group
    phys_vol = new_resource.phys_vol
    log_vol = new_resource.log_vol
    vol_size = new_resource.vol_size
    fs_type = new_resource.fs_type
    mount_point = new_resource.mount_point

    # create volume group
    lvm_volume_group vol_group do
      # create physical volume
      physical_volumes [phys_vol]

      # create logical volume
      logical_volume log_vol do
        size vol_size
        filesystem fs_type
        mount_point mount_point
      end
  end
end
```

**my_cookbook/recipes/diskmnt.rb**

```
my_cookbook_diskmnt 'Setup data disk' do
  vol_group   'vg_data'
  phys_vol    '/dev/sdb'
  log_vol     'lv_data'
  vol_size    '100%VG'
  fs_type     'ext4'
  mount_point '/mnt/data'
end
```
### Expected Result:

The custom resource/provider should pass the arguments through to the lvm provider and create the volume group with the logical volume and mount it at the mount point.
### Actual Result:

I get the error `No resource or method named 'new_resource' for 'Chef::Resource::LvmLogicalVolume "lv_data"'`

**Comment by gawbul** [comment]
@tas50 sorry to ping you directly... any help here should be greatly appreciated though - am I doing something stupid here?

**Comment by gawbul** [comment]
Doing the following solves the problem, but I aren't quite sure why?

```
action :create do
  # only run if we're set to
  if node['my_cookbook']['diskmnt'] == true
    # install relevant packages and gems
    include_recipe 'lvm::default'

    this_resource = new_resource
    vol_group = this_resource.vol_group
    phys_vol = this_resource.phys_vol
    log_vol = this_resource.log_vol
    vol_size = this_resource.vol_size
    fs_type = this_resource.fs_type
    mount_point = this_resource.mount_point

    # create volume group
    lvm_volume_group vol_group do
      # create physical volume
      physical_volumes [phys_vol]

      # create logical volume
      logical_volume log_vol do
        size vol_size
        filesystem fs_type
        mount_point mount_point
      end
  end
end
```

**Comment by tas50** [comment]
@gawbul Can you give this a try with the 4.X release?

**Comment by iennae** [comment]
This should be resolved with the latest release of this cookbook. If you are still having issues please reopen! Thanks so much.
