### ISSUE TITLE
No resource or method named `platform_family?`

### ISSUE THREAD

**Issue by jeremymv2** [chef-cookbooks/lvm#115]
### Cookbook version
4.0.2

### Chef-client version
12.6

### Platform Details
N/A

### Issue:
```
================================================================================
Error executing action `create` on resource 'lvm_logical_volume[volume]'
================================================================================

NoMethodError
-------------
No resource or method named `platform_family?' for `Chef::Provider::LvmLogicalVolume ""'

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:221:in `install_filesystem_deps'
/tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:47:in `action_create'`
```

**Comment by tas50** [comment]
Shipped in 4.0.3. Thanks
