### ISSUE TITLE
In Chef 13 cannot find the vgs command. Works in Chef 12.

### ISSUE THREAD

**Issue by chilicheech** [chef-cookbooks/lvm#133]
### Cookbook version
4.1.4

### Chef-client version
13.2.20

### Platform Details
RHEL 7.1

### Scenario:
Create a volume group.

### Steps to Reproduce:
Run `sudo chef-client -c /etc/chef/client.rb -l auto` from a CI build.

### Expected Result:
Converges fine from a CI build.

### Actual Result:
```
17:06:52                           * lvm_volume_group[sys] action create
17:06:52                             * chef_gem[chef-ruby-lvm-attrib] action install (up to date)
17:06:52                             * chef_gem[chef-ruby-lvm] action install (up to date)
17:06:52                             
17:06:52                             ================================================================================
17:06:52                             Error executing action `create` on resource 'lvm_volume_group[sys]'
17:06:52                             ================================================================================
17:06:52                             
17:06:52                             Errno::ENOENT
17:06:52                             -------------
17:06:52                             No such file or directory - vgs
17:06:52                             
17:06:52                             Cookbook Trace:
17:06:52                             ---------------
17:06:52                             /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:125:in `create_volume_group'
17:06:52                             /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:60:in `action_create'
17:06:52                             
17:06:52                             Resource Declaration:
17:06:52                             ---------------------
17:06:52                             # In /var/chef/cache/cookbooks/yahoo-ss-smashhome/recipes/partition_setup.rb
17:06:52                             
17:06:52                              11: lvm_volume_group 'sys' do
17:06:52                              12:   physical_volumes '/dev/sda3'
17:06:52                              13: end
17:06:52                              14: 
17:06:52                             
17:06:52                             Compiled Resource:
17:06:52                             ------------------
17:06:52                             # Declared in /var/chef/cache/cookbooks/yahoo-ss-smashhome/recipes/partition_setup.rb:11:in `from_file'
17:06:52                             
17:06:52                             lvm_volume_group("sys") do
17:06:52                               provider Chef::Provider::LvmVolumeGroup
17:06:52                               action :create
17:06:52                               default_guard_interpreter :default
17:06:52                               declared_type :lvm_volume_group
17:06:52                               cookbook_name "yahoo-ss-smashhome"
17:06:52                               recipe_name "partition_setup"
17:06:52                               physical_volumes "/dev/sda3"
17:06:52                             end
17:06:52                             
17:06:52                             System Info:
17:06:52                             ------------
17:06:52                             chef_version=13.2.20
17:06:52                             platform=redhat
17:06:52                             platform_version=7.1
17:06:52                             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
17:06:52                             program_name=chef-client worker: ppid=13881;start=00:06:30;
17:06:52                             executable=/opt/chef/bin/chef-client
```

This was working fine with chef 12. I've done a little debugging and it looks like the PATH environment variable is different in chef 12 and chef 13.

In Chef 12 the PATH is `/usr/local/bin:/usr/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin:/usr/local/sbin:/usr/sbin:/sbin:/bin` on my system during the chef run.
In Chef 13 the PATH is `/usr/local/bin:/usr/bin` during the chef run.

The `vgs` command is located in `/usr/sbin/vgs` and `/sbin/vgs`. What can I do to make this work?

**Comment by chilicheech** [comment]
This may be related to this change: https://github.com/chef/chef/commit/d24976bbd8846a60d186790f38124f312e91473d#diff-d19a42ae266a2919d7cfeb43c77dbaffL253
Looks like the path isn't being sanitized by default anymore.

**Comment by tas50** [comment]
@chilicheech What's that $PATH variable look like on your system?

**Comment by chilicheech** [comment]
@tas50 When I ssh to the box and get a login shell the path is: `/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin`
Without a login shell, such as when running `ssh username@hostname sudo chef-client` from a CI build, the path is: `/usr/local/bin:/usr/bin`

**Comment by taharah** [comment]
Just ran into this same issue on Chef 13.6

**Comment by tas50** [comment]
If you upgrade to a later Chef 13 release this will be resolved.
