### ISSUE TITLE
LVM v4.1.10 Raise Syntax is Incorrect

### ISSUE THREAD

**Issue by wheatevo** [chef-cookbooks/lvm#141]
### Cookbook version
4.1.10

### Chef-client version
12.18.31/14.0.120

### Platform Details
RHEL/OEL 7.4

### Scenario:
When exceptions are encountered for an LV creation or resize due to insufficient space, the following exception is raised instead of the more descriptive exception: `TypeError: exception class/object expected`. Would instead expect this to raise one of the messages within the lvm_logical_volume provider such as `"Error trying to extend logical volume #{lv.name} beyond the capacity of volume group #{group}"`.

### Steps to Reproduce:
Attempt to resize an LV with the cookbook to a size beyond the capacity of its containing volume group and examine the chef-client output.

### Expected Result:
This should return the actual exception message instead of an exception due to incorrect `raise` syntax.

### Actual Result:
```
testnode.test.com     * lvm_logical_volume[testlv02-testing] action resize
testnode.test.com       
testnode.test.com       ================================================================================
testnode.test.com       Error executing action `resize` on resource 'lvm_logical_volume[testlv02-testing]'
testnode.test.com       ================================================================================
testnode.test.com       
testnode.test.com       TypeError
testnode.test.com       ---------
testnode.test.com       exception class/object expected
testnode.test.com       
testnode.test.com       Cookbook Trace:
testnode.test.com       ---------------
testnode.test.com       /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:201:in `raise'
testnode.test.com       /var/chef/cache/cookbooks/lvm/libraries/provider_lvm_logical_volume.rb:201:in `action_resize'
testnode.test.com       
testnode.test.com       Resource Declaration:
testnode.test.com       ---------------------
testnode.test.com       # In /var/chef/cache/cookbooks/cwxtiauto_lvm/resources/cwx_lv.rb
testnode.test.com       
testnode.test.com       131:   lvm_logical_volume lv_name do
testnode.test.com       132:     action             lv_action
testnode.test.com       133:     group              lv_vg
testnode.test.com       134:     size               lv_size
testnode.test.com       135:     filesystem         lv_filesystem unless swap_lv
testnode.test.com       136:     filesystem_params  lv_filesystem_params if lv_filesystem_params && !swap_lv
testnode.test.com       137:     mount_point        lv_mount_point unless swap_lv
testnode.test.com       138:     physical_volumes   lv_pvs if lv_pvs
testnode.test.com       139:     stripes            lv_stripes if lv_stripes
testnode.test.com       140:     stripe_size        lv_stripe_size if lv_stripe_size
testnode.test.com       141:     mirrors            lv_mirrors if lv_mirrors
testnode.test.com       142:     contiguous         lv_contiguous if lv_contiguous
testnode.test.com       143:     readahead          lv_readahead if lv_readahead
testnode.test.com       144:     take_up_free_space lv_fill_freespace if lv_fill_freespace
testnode.test.com       145:     wipe_signatures    lv_wipe_signatures
testnode.test.com       146:     notifies :reload, "ohai[reload_#{filesystem_node_entry}]", :immediately
testnode.test.com       147:   end
testnode.test.com       148: 
testnode.test.com       
testnode.test.com       Compiled Resource:
testnode.test.com       ------------------
testnode.test.com       # Declared in /var/chef/cache/cookbooks/cwxtiauto_lvm/resources/cwx_lv.rb:131:in `block in class_from_file'
testnode.test.com       
testnode.test.com       lvm_logical_volume("testlv02-testing") do
testnode.test.com         provider Chef::Provider::LvmLogicalVolume
testnode.test.com         action [:resize]
testnode.test.com         retries 0
testnode.test.com         retry_delay 2
testnode.test.com         default_guard_interpreter :default
testnode.test.com         declared_type :lvm_logical_volume
testnode.test.com         cookbook_name "cwx_millennium_provision"
testnode.test.com         group "testvg"
testnode.test.com         size "30G"
testnode.test.com         filesystem "ext4"
testnode.test.com         mount_point {:location=>"/testing", :dump=>0, :pass=>0}
testnode.test.com         wipe_signatures true
testnode.test.com       end
testnode.test.com       
testnode.test.com       Platform:
testnode.test.com       ---------
testnode.test.com       x86_64-linux
testnode.test.com       
```

**Comment by wheatevo** [comment]
This appears to be caused by the second argument within the `raise` statement here: https://github.com/chef-cookbooks/lvm/blob/master/libraries/provider_lvm_logical_volume.rb#L201

`raise("Error trying to extend logical volume #{lv.name} beyond the capacity of volume group #{group}", 2) if !thin_volume? && (lv_size_req - lv_size_cur) > pe_free`

```
raise('my exception', 2)
TypeError: exception class/object expected
        from (irb):8:in `raise'
        from (irb):8
        from /opt/chef/embedded/bin/irb:11:in `<main>'
```

```
raise('my exception')
RuntimeError: my exception
        from (irb):7
        from /opt/chef/embedded/bin/irb:11:in `<main>'
```

Per the Ruby documentation, this does not appear to be valid raise calling syntax: https://ruby-doc.org/core-2.3.1/Kernel.html#method-i-raise
