### ISSUE TITLE
Extend action on lvm_volume_group fails with a uninitialized constant NameError

### ISSUE THREAD

**Issue by ninadsp** [chef-cookbooks/lvm#54]
Scenario: Base VM image consists of volume group `vg0`, which contains a logical volume `var`. The base image does not have sufficient space for my requirements, so I attached a disk to the VM at `/dev/vardata0`. The following code snippet to extend the VG fails:

``` ruby
volumes = Dir.glob("/dev/vardata*")
lvm_volume_group "vg0" do
    physical_volumes volumes
    action :extend
end
```

The error is:

```
[2015-03-19T06:53:09+00:00] INFO: Processing lvm_volume_group[vg0] action extend (my-server::service_linux_config line 6)

================================================================================ 
Error executing action `extend` on resource 'lvm_volume_group[vg0]' 
================================================================================ 


NameError 
--------- 
uninitialized constant Chef::Provider::LvmVolumeGroup::LVM 


Cookbook Trace: 
--------------- 
/var/lib/scratch/repos/ninadsp/servicedev/chef/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:69:in `action_extend' 


Resource Declaration: 
--------------------- 
# In /var/lib/scratch/repos/ninadsp/servicedev/chef/site-cookbooks/my-server/recipes/service_linux_config.rb

  6: lvm_volume_group "vg0" do
  7:     physical_volumes volumes
  8:     action :extend
  9:     notifies :resize, 'lvm_logical_volume[/dev/vg0/var]', :immediately



Compiled Resource: 
------------------ 
# Declared in /var/lib/scratch/repos/ninadsp/servicedev/lsdev/chef/site-cookbooks/my-server/recipes/service_linux_config.rb:6:in `from_file'

lvm_volume_group("vg0") do
  provider Chef::Provider::LvmVolumeGroup
  action [:extend]
  retries 0
  retry_delay 2
  cookbook_name :"my-server"
  recipe_name "service_linux_config"
  physical_volumes ["/dev/vardata0"]
end
```

Looking at the definition of `action_extend`, the error is reported at [Line 69](https://github.com/opscode-cookbooks/lvm/blob/master/libraries/provider_lvm_volume_group.rb#L69). Is it because the lvm gem is not imported in this method? Or does the `action_create` [import the gem](https://github.com/opscode-cookbooks/lvm/blob/master/libraries/provider_lvm_volume_group.rb#L44) wrongly, and it should be imported during the initialization of `LvmVolumeGroup`?

**Comment by tas50** [comment]
This is no longer an issue
