### ISSUE TITLE
Proper way to unit test logical_volume nested in volume group

### ISSUE THREAD

**Issue by chazzly** [chef-cookbooks/lvm#63]
I have the following in a recipe:

```
lvm_volume_group 'jenkinsvg' do
  physical_volumes ['/dev/sdb']

  logical_volume 'jenkinslv' do
    size        '10G'
    filesystem  'ext4'
    mount_point location: '/apps/jenkins'
  end

  logical_volume 'buildlv' do
    size        '150G'
    filesystem  'ext4'
    mount_point location: '/build'
  end
end
```

And to unit test (rspec / chefspec)

```
it 'creates volume_group' do
  expect(chef_run).to create_lvm_volume_group('jenkinsvg').with(physical_volumes: ['/dev/sdb'])
end

it 'creates jenkins lv' do
  expect(chef_run).to create_lvm_logical_volume('jenkinslv').with(
    size: '20G',
    filesystem: 'ext4',
    mount_point: '/apps/jenkins'
  )
end
```

The volume group passes, but the logical volume comes back with this error:

```
 expected "lvm_logical_volume[jenkinslv]" actions [] to include :create
```

I then tried re-working the logical_volume as a property of the volume group test.  I've tried various ways of formatting it, but I can't find the right one.  The response I get is something like:

```
 expected "lvm_volume_group[jenkinsvg]" to have parameters:

         logical_volumes [{:name=>"jenkinslv", :size=>"20G", :filesystem=>"ext4", :mount_point=>"/apps/jenkins"}],
was [<lvm_logical_volume[jenkinslv] @performed_actions: {} @name: "jenkinslv" @noop: nil @before: nil @params: {} @provider: Chef::Provider::LvmLogicalVolume @allowed_actions: [:nothing, :create, :resize] @action: [:nothing] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/home/cruhl/chef-cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :lvm_logical_volume @declared_type: :lvm_logical_volume @cookbook_name: :"cars-jenkins" @recipe_name: "master" @size: "20G" @filesystem: "ext4" @mount_point: {:location=>"/apps/jenkins"}>, <lvm_logical_volume[buildlv] @performed_actions: {} @name: "buildlv" @noop: nil @before: nil @params: {} @provider: Chef::Provider::LvmLogicalVolume @allowed_actions: [:nothing, :create, :resize] @action: [:nothing] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/home/cruhl/chef-cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :lvm_logical_volume @declared_type: :lvm_logical_volume @cookbook_name: :"cars-jenkins" @recipe_name: "master" @size: "80G" @filesystem: "ext4" @mount_point: {:location=>"/build"}>, <lvm_logical_volume[tomcatlv] @performed_actions: {} @name: "tomcatlv" @noop: nil @before: nil @params: {} @provider: Chef::Provider::LvmLogicalVolume @allowed_actions: [:nothing, :create, :resize] @action: [:nothing] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/home/cruhl/chef-cookbooks/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :lvm_logical_volume @declared_type: :lvm_logical_volume @cookbook_name: :"cars-jenkins" @recipe_name: "master" @size: "5G" @filesystem: "ext4" @mount_point: {:location=>"/apps/tomcat"}>]
```

Does anyone know what the correct "rspec/chefspec" format for this test would be?  Is there a better way to test this?  I tried using Step_into, but that didn't seem to make much difference (besides, I'm not trying to test the LVM lwrp, just that I'm passing it what I'm supposed to be).

Thanks

**Comment by MarkGibbons** [comment]
@chazzly I don't think chefspec will see the lvm_logical_volumes.  Those resources get created during the processing of the volume_group resource provider.  You might try a spec something like:
it 'creates volume_group' do
  expect(chef_run).to create_lvm_volume_group('jenkinsvg').with(logical_volume)
end

logical volume is a resource attribute, just like physical_volumes.  I don't know about how to specify the value of the logical_volume for a test, but maybe this would get you started.

**Comment by davecozz** [comment]
I ran into this same issue and could not find a working solution other than pulling the `logical_volume` attribute out of the `lvm_volume_group` resource and using a separate `lvm_logical_volume` resource only so that I could test it. It would be nice if something like this would work (as @MarkGibbons suggested):   
```
it 'create my volume group' do
  expect(chef_run).to create_lvm_volume_group('my_vg').with(
    logical_volume: 'my_lv'
  )
end
```
unfortunately, it throws this error:
```
Failures:

  1) my-cookbook::lvm-storage create instances volume group
     Failure/Error:
       expect(chef_run).to create_lvm_volume_group('my_vg').with(
         logical_volume: 'my_lv'
       )

     ArgumentError:
       wrong number of arguments (0 for 1)
     # /var/folders/4p/flzkxrk1023b33pvgtqy2gfckstgyb/T/d20160226-16282-14f13zf/cookbooks/lvm/libraries/resource_lvm_volume_group.rb:108:in `logical_volume'
    ...
```

**Comment by tas50** [comment]
Due to the way the volume resource is grouped inside the group resource ChefSpec won't be able to see the volume. Unfortunately you can't test this as-is.
