### ISSUE TITLE
problems with lvm cookbook when running under chefspec

### ISSUE THREAD

**Issue by rhb84** [chef-cookbooks/lvm#71]
Hi 

I seem to have a problem running lvm cookbook under chefspec so the problem might not be directly related to lvm itself.
When I'm loading a recipe containing lvm resource "lvm_logical_volume" into chefspec I'm getting the following error:
```
================================================================================
Recipe Compile Error in /tmp/d20151104-32398-1ht9l5d/cookbooks/hc_lvm/recipes/update_ext_var.rb
================================================================================

TypeError
---------
no implicit conversion of Symbol into Integer

Cookbook Trace:
---------------
  /tmp/d20151104-32398-1ht9l5d/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:158:in `[]'
  /tmp/d20151104-32398-1ht9l5d/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:158:in `block in mount_point'
  /tmp/d20151104-32398-1ht9l5d/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:147:in `mount_point'
  /tmp/d20151104-32398-1ht9l5d/cookbooks/hc_lvm/recipes/update_ext_var.rb:82:in `block in from_file'
  /tmp/d20151104-32398-1ht9l5d/cookbooks/hc_lvm/recipes/update_ext_var.rb:78:in `from_file'

Relevant File Content:
----------------------
/tmp/d20151104-32398-1ht9l5d/cookbooks/lvm/libraries/resource_lvm_logical_volume.rb:

151:            :callbacks => {
152:              ': location is required!' => proc do |value|
153:                value.class == String || (value[:location] && !value[:location].empty?)
154:              end,
155:              ': location must be an absolute path!' => proc do |value|
156:                # this can be a string or a hash, so attempt to match either for
157:                # the regex
158>>               matches = value =~ %r{^/[^\0]*} || value[:location] =~ %r{^/[^\0]*}
159:                !matches.nil?
160:              end
161:            }
162:          )
163:        end
164:
165:        # Attribute: physical_volumes - list of physical volumes to be used for creation
166:        #
167:        # @param arg [String, Array] - list of physical devices

F

Failures:

  1) hc_lvm::update_ext_var runs ruby block populate_partition_var
     Failure/Error: end.converge(described_recipe) }
     TypeError:
       no implicit conversion of Symbol into Integer
```

I'm not even defining any tests yet for this resource - just loaded the recipe using 'describe' block.

Here is my problematic recipe (update_ext_var.rb):

```
  ruby_block 'populate_partition_var' do
      block do
        Chef::Log.info("for partition... #{node['test_lvm']['var_vol_name']}")
        # tricky way to load this Chef::Mixin::ShellOut utilities
        Chef::Resource::RubyBlock.send(:include, Chef::Mixin::ShellOut)
        # Get Device path from mount point
        dpath_cmd = "df -Ph #{node['test_lvm']['var_vol_name']}|tail -1| cut -f 1 -d ' '"
        dpath = shell_out(dpath_cmd).stdout

        # Check if the device path is exist, then proceed further.
        unless dpath.nil?
          dpath = dpath.strip
          lvmpath_cmd = "lvdisplay -c #{dpath} | cut -d ':' -f 1"
          lvmpath = shell_out(lvmpath_cmd).stdout
          lvmgrp = ''
          lvname = ''
          unless lvmpath.nil?
            lvmpath = lvmpath.strip
            # Get volume group of the device path
            lvmgrp_cmd = "lvdisplay -c #{dpath}|cut -d ':' -f 2"
            lvmgrp = shell_out(lvmgrp_cmd).stdout

            # Get LV Name
            lvname_cmd = "lvs  --noheadings -o lv_name #{lvmpath}"
            lvname = shell_out(lvname_cmd).stdout
          end
          # Get FS Name
          lvfs_cmd = "df -T #{node['test_lvm']['var_vol_name']} | awk '{print $1}' | tail -n1"
          lvfs = shell_out(lvfs_cmd).stdout

          node.default['test_lvm']['var_dev_path'] = dpath
          node.default['test_lvm']['var_lvm_path'] = lvmpath
          node.default['test_lvm']['var_grp'] = lvmgrp.strip
          node.default['test_lvm']['var_logical_volume'] = lvname.strip
          node.default['test_lvm']['var_fs'] = lvfs.strip
        end
      end
      action :create
      only_if "mountpoint -q #{node['test_lvm']['var_vol_name']}"
  end.run_action(:create)

  ruby_block 'var_partitions_info' do
    block do
      Chef::Log.info("lvm_grp=#{node.default['test_lvm']['var_grp']}")
      Chef::Log.info("logical_volume=#{node.default['test_lvm']['var_logical_volume']}")
      Chef::Log.info("lvm_path=#{node.default['test_lvm']['var_lvm_path']}")
      Chef::Log.info("device_path=#{node.default['test_lvm']['var_dev_path']}")
      Chef::Log.info("fs=#{node.default['test_lvm']['var_fs']}")
      Chef::Log.info("options=#{node.default['test_lvm']['var_options']}")
      Chef::Log.info("dump=#{node.default['test_lvm']['var_dump']}")
      Chef::Log.info("pass=#{node.default['test_lvm']['var_pass']}")
    end
    action :run
  end

  # remount /var
  execute 'remount_var' do
    command "mount -o remount #{node['test_lvm']['var_vol_name']}"
    action :nothing
  end

  # Take off noexec from /var amd /tmp and remount
  Chef::Log.info('Take off noexec from /var and remount.')
  mount node['test_lvm']['var_vol_name'] do
    device node['test_lvm']['var_dev_path']
    fstype node['test_lvm']['var_fs']
    options node['test_lvm']['var_options']
    dump node['test_lvm']['var_dump'].to_i
    pass node['test_lvm']['var_pass'].to_i
    notifies :run, 'execute[remount_var]', :immediately
    action [:mount, :enable]
    only_if "mount|grep #{node['test_lvm']['var_dev_path']}|grep noexec"
  end

  if ENV['APP_DB'] != '1'
    Chef::Log.info('Assigning remaining disk space to  /var ....')

    lvm_logical_volume node['test_lvm']['var_logical_volume'] do
      group node['test_lvm']['var_grp']
      take_up_free_space true
      filesystem node['test_lvm']['var_fs']
      mount_point node['test_lvm']['var_vol_name']
      size '25%VG'
      action :resize
      only_if "mountpoint -q #{node['test_lvm']['var_vol_name']}"
    end
  end
```

Here is my chefspec test:

```
require 'spec_helper'

describe 'test_lvm::update_ext_var' do
  ENV['APP_DB'] = '1'
  let(:chef_run) { ChefSpec::SoloRunner.new(platform: 'oracle', version: '6.5') do |node|
    node.set['test_lvm']['var_vol_name'] = 'var_vol_name'
    node.set['test_lvm']['var_logical_volume'] = 'var_logical_volume'
  end.converge(described_recipe) }

  before do
    stub_command("mountpoint -q var_vol_name").and_return(true)
    allow(chef_run).to receive(lvm_logical_volume).and_return(true)
  end

  it 'runs ruby block populate_partition_var' do
    expect(chef_run).to run_ruby_block('populate_partition_var')
  end
  ENV['APP_DB'] = ''
end
```

As you can see above I'm not even defined a test for that resource yet so I think the problem is with converging the recipe in memory so most probably this is only visible in chefspec.

**Comment by gregsymons** [comment]
So, the problem with your test code is that you're not setting the mount point to an absolute path.

However, the provider shouldn't blow up when you do that; it should give you a more reasonable error message. I've fixed the issue in the lvm resource code, but you'll have to fix your test.

**Comment by gregsymons** [comment]
Also, you might what to consider using the `di-ruby-lvm` wrapper around lvm rather than doing all that ugly shelling out in your ruby block. It's already installed by the lvm cookbook, so as long as `lvm::default` comes before your recipe, it should be usable.
