### ISSUE TITLE
undefined method `mount'

### ISSUE THREAD

**Issue by Puneeth-n** [chef-cookbooks/lvm#90]
````
    ================================================================================
    Error executing action `create` on resource 'lvm_volume_group[storagevg]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `mount' for #<Chef::Provider::LvmVolumeGroup:0x00000007a55378>

    Cookbook Trace:
    ---------------
    /home/ubuntu/chef-solo/cookbooks-3/lvm/libraries/provider_lvm_volume_group.rb:109:in `block in create_mount_resource'
    /home/ubuntu/chef-solo/cookbooks-3/lvm/libraries/provider_lvm_volume_group.rb:103:in `each'
    /home/ubuntu/chef-solo/cookbooks-3/lvm/libraries/provider_lvm_volume_group.rb:103:in `create_mount_resource'
    /home/ubuntu/chef-solo/cookbooks-3/lvm/libraries/provider_lvm_volume_group.rb:48:in `action_create'

    Resource Declaration:
    ---------------------
    # In /home/ubuntu/chef-solo/cookbooks-2/tm-box-elasticsearch-event-logs-master/recipes/attach_raid.rb

     13: lvm_volume_group 'storagevg' do
     14:   physical_volumes node['tm-box-elasticsearch-event-logs-master']['physical_volumes']
     15:   logical_volume 'storagelv' do
     16:     size '100%VG'
     17:     filesystem 'xfs'
     18:     mount_point node['tm-box-elasticsearch-event-logs-master']['storage_dir']
     19:     stripes node['tm-box-elasticsearch-event-logs-master']['physical_volumes'].length
     20:   end
     21: end

    Compiled Resource:
    ------------------
    # Declared in /home/ubuntu/chef-solo/cookbooks-2/tm-box-elasticsearch-event-logs-master/recipes/attach_raid.rb:13:in `from_file'

    lvm_volume_group("storagevg") do
      provider Chef::Provider::LvmVolumeGroup
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      logical_volumes [<lvm_logical_volume[storagelv] @name: "storagelv" @noop: nil @before: nil @params: {} @provider: Chef::Provider::LvmLogicalVolume @allowed_actions: [:nothing, :create, :resize] @action: [:nothing] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/home/ubuntu/chef-solo/cookbooks-3/lvm/libraries/resource_lvm_volume_group.rb:110:in `logical_volume'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0.000373769 @sensitive: false @resource_name: :lvm_logical_volume @declared_type: :lvm_logical_volume @cookbook_name: :"tm-box-elasticsearch-event-logs-master" @recipe_name: "attach_raid" @size: "100%VG" @filesystem: "xfs" @mount_point: "/vol" @stripes: 2>]
      declared_type :lvm_volume_group
      cookbook_name :"tm-box-elasticsearch-event-logs-master"
      recipe_name "attach_raid"
      physical_volumes ["/dev/xvdb", "/dev/xvdc"]
    end
````

**Comment by Puneeth-n** [comment]
Resolved this error by updating to the latest release of the cookbook.
